### ISSUE TITLE
Alignment problem in home, only on Chrome.

### ISSUE THREAD

**Issue by gmcinalli** [daniele-orlando/www.studiodentisticogattone.it#1]
Chrome:
![image](https://user-images.githubusercontent.com/9024983/35327512-09c8d71c-00fa-11e8-9c2a-cbc1c56538c3.png)

Safari:
![image](https://user-images.githubusercontent.com/9024983/35327591-4b425218-00fa-11e8-9d45-0b2a5838b283.png)

**Comment by daniele-orlando** [comment]
I have been able to reproduce the problem. Thank you very much for your valuable feedback.
